import Wrapper from '@/components/dashboard/Wrapper'
import Head from 'next/head'
import MainLayout from '../../components/layout/MainLayout'
import { parseCookies } from '@/helpers/index'
import { API_URL, DASH_PER_PAGE } from '@/config/index'
import EachInstution from '@/components/institution/eachInstution'

export default function Institutions({ institutions, page, total }) {
  // console.log(institutions)
  return (
    <MainLayout>
      <Head>
        <title>Institutions & Homes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper title="Institutions & Homes">
        <hr className="border-gray-300 mb-2 sm:hidden block"></hr>
        {institutions?.map((inst) => (
          <div key={inst.id} className="grid grid-cols-1 border-gray-200">
            <EachInstution institution={inst} />
          </div>
        ))}
      </Wrapper>
    </MainLayout>
  )
}

export async function getServerSideProps({ req, query: { page = 1 } }) {
  const { token } = parseCookies(req)

  if (!token) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  const start = +page === 1 ? 0 : (+page - 1) * DASH_PER_PAGE

  // Fetch total/count
  const totalRes = await fetch(`${API_URL}/institutions/count`, {
    method: 'GET',
    headers: {
      Authorization: `Bearer ${token}`,
    },
  })
  const total = await totalRes.json()

  const res = await fetch(
    `${API_URL}/institutions?_limit=${DASH_PER_PAGE}&_start=${start}`,
    // `${API_URL}/institutions`,
    {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${token}`,
      },
    },
  )
  const institutions = await res.json()

  return {
    props: {
      institutions,
      page: +page,
      total,
    },
  }
}
