import Head from 'next/head'
import MainLayout from '@/components/layout/MainLayout'
import { API_URL } from '@/config/index'
import EachItem from '@/components/each-item/EachItem'

function item({ item }) {
  return (
    <MainLayout>
      <Head>
        <title>{item.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EachItem item={item} />
    </MainLayout>
  )
}

export async function getServerSideProps({ query: { slug } }) {
  const res = await fetch(`${API_URL}/items?slug=${slug}`)
  const item = await res.json()
  return {
    props: {
      item: item[0],
    },
  }
}

export default item
