import MainLayout from '../../../components/layout/MainLayout'
import Head from 'next/head'
import Wrapper from '@/components/all-items/Wrapper'
import { API_URL } from '@/config/index'
import EachItem from '@/components/all-items/EachItem'

export default function items({ items }) {
  return (
    <MainLayout>
      <Head>
        <title>All Items</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper title="All Items">
        {items.map((item) => (
          <EachItem key={item.id} item={item} />
        ))}
      </Wrapper>
    </MainLayout>
  )
}

export async function getServerSideProps() {
  const res = await fetch(`${API_URL}/items?_sort=created_at:ASC`)
  const items = await res.json()
  return {
    props: {
      items,
    },
  }
}
