import MainLayout from '../../../components/layout/MainLayout'
import Head from 'next/head'
import Wrapper from '@/components/all-items/Wrapper'
import { API_URL } from '@/config/index'
import EachItem from '@/components/all-items/EachItem'
import { parseCookies } from '@/helpers/index'

export default function items({ items }) {
  return (
    <MainLayout>
      <Head>
        <title>All Items</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper title="Available Items">
        {items.length !== 0 &&
          items.map((item) => <EachItem key={item.id} item={item} />)}
      </Wrapper>
    </MainLayout>
  )
}

export async function getServerSideProps({ req }) {
  const { token } = parseCookies(req)

  if (!token) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  const res = await fetch(`${API_URL}/items?_sort=created_at:ASC`, {
    method: 'GET',
    headers: {
      Authorization: `Bearer ${token}`,
    },
  })
  const items = await res.json()

  return {
    props: {
      items,
    },
  }
}
