import Head from 'next/head'
import MainLayout from '@/components/layout/MainLayout'
import { API_URL } from '@/config/index'
import EachItem from '@/components/each-item/EachItem'
import { parseCookies } from 'helpers'

function item({ item }) {
  return (
    <MainLayout>
      <Head>
        <title>{item.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EachItem item={item} />
    </MainLayout>
  )
}

export async function getServerSideProps({ query: { slug }, req }) {
  const { token } = parseCookies(req)

  if (!token) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  const res = await fetch(`${API_URL}/items?slug=${slug}`, {
    method: 'GET',
    headers: {
      Authorization: `Bearer ${token}`,
    },
  })
  const item = await res.json()
  return {
    props: {
      item: item[0],
    },
  }
}

export default item
