import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Index/Hero'
import Footer from '../components/layout/Footer'
import Layout from '../components/layout/Layout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </Layout>
  )
}
