import Wrapper from '@/components/dashboard/Wrapper'
import MainLayout from '@/components/layout/MainLayout'
import Head from 'next/head'
import { useContext } from 'react'
import AuthContext from '@/context/AuthContext'

export default function Dashboard({}) {
  const { user, logout } = useContext(AuthContext)
  console.log(user)

  return (
    <MainLayout>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper title="Profile">{/*  */}</Wrapper>
    </MainLayout>
  )
}
