import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState, useEffect, useContext } from 'react'
import toast, { Toaster } from 'react-hot-toast'
import AuthContext from '@/context/AuthContext'

export default function RegisterPage() {
  const [username, setUsername] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [password2, setPassword2] = useState('')

  const { register, error } = useContext(AuthContext)

  useEffect(() => error && toast.error(error))

  const handleSubmit = (e) => {
    e.preventDefault()

    //validation
    const hasEmptyFields = Object.values({
      username,
      email,
      password2,
      password,
    }).some((element) => element === '')
    if (hasEmptyFields) {
      toast.error('Please fill in all fields')
      return
    }

    if (password !== password2) {
      toast.error('Passwords do not match.')
      return
    }

    register({ username, email, password })
  }
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="absolute w-full h-full sm:bg-gray-100 font-medium text-sm sm:mt-0 mt-8">
        <Toaster />
        <div className="sm:container mx-auto px-4 h-full">
          <div className="sm:flex content-center items-center justify-center h-full">
            <div className="-full sm:w-8/12 md:w-7/12 lg:w-5/12 xl:w-2/7 sm:px-4">
              <div className="sm:flex flex-col min-w-0 break-words w-full mb-6 sm:rounded-sm bg-white sm:border sm:border-gray-300">
                <div className="rounded-t mb-0 px-4 sm:px-6 pt-6">
                  <div className="flex flex-wrap my-4">
                    <div className="w-1/2">
                      <div className="ml-0 text-xl">
                        <h2 className="text-gray-600 font-semibold">
                          Register
                        </h2>
                      </div>
                    </div>
                    <div className="w-1/2 text-right">
                      <Link href="/login">
                        <a className="text-gray-600 font-bold mr-0 sm:mr-4">
                          <small>Log in here?</small>
                        </a>
                      </Link>
                    </div>
                  </div>
                </div>
                <div className="flex-auto px-4 sm:px-7 py-3">
                  <form onSubmit={handleSubmit}>
                    <div className="relative w-full mb-3">
                      <label
                        className="block text-gray-600 mb-2"
                        htmlFor="grid-2"
                      >
                        First & Last Name*
                      </label>
                      <input
                        type="text"
                        className="input-styles"
                        placeholder="Your username"
                        value={username}
                        onChange={(e) => setUsername(e.target.value)}
                        style={{ transition: 'all .15s ease' }}
                      />
                    </div>
                    <div className="relative w-full mb-3">
                      <label
                        className="bblock text-gray-600 mb-2"
                        htmlFor="grid-password"
                      >
                        Email*
                      </label>
                      <input
                        type="email"
                        className="input-styles"
                        placeholder="yournames@example.com"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        style={{ transition: 'all .15s ease' }}
                      />
                    </div>

                    <div className="relative w-full mb-3">
                      <label
                        className="block text-gray-600 mb-2"
                        htmlFor="grid-password"
                      >
                        Password*
                      </label>
                      <input
                        type="password"
                        className="input-styles"
                        placeholder="Type your password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        style={{ transition: 'all .15s ease' }}
                      />
                    </div>
                    <div className="relative w-full mb-3">
                      <label
                        className="block text-gray-600 mb-2"
                        htmlFor="grid-password"
                      >
                        Password Again*
                      </label>
                      <input
                        type="password"
                        className="input-styles"
                        placeholder="Type your password again"
                        value={password2}
                        onChange={(e) => setPassword2(e.target.value)}
                        style={{ transition: 'all .15s ease' }}
                      />
                    </div>
                    <div className="text-center mt-6">
                      <button
                        className="btn-yellow-forms"
                        type="submit"
                        style={{ transition: 'all .15s ease' }}
                      >
                        Register
                      </button>
                    </div>
                  </form>

                  <div className="text-gray-500 text-center my-1 font-semibold">
                    <small>OR</small>
                  </div>

                  <button
                    className="btn-login-register mb-8"
                    type="button"
                    style={{ transition: 'all .15s ease' }}
                  >
                    <Image
                      alt="..."
                      className="w-full"
                      src="/google.svg"
                      width={15}
                      height={15}
                    />
                    <div className="pr-2"></div>
                    Sign up with Google
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
