import Head from 'next/head'
import { FaSave } from 'react-icons/fa'
import MainLayout from '../../components/layout/MainLayout'

function give() {
  return (
    <MainLayout>
      <Head>
        <title>Give Items</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font relative">
        <div className="container px-5 py-10 mx-auto">
          <div className="flex flex-col text-center w-full mb-12">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
              Give an Item
            </h1>
            <p className="lg:w-2/3 mx-auto leading-relaxed text-base">
              You will be required to pay 50 ksh. This is for the maintenance of
              the website and for keeping this project going. Thank you.
            </p>
          </div>
          <div className="lg:w-1/2 md:w-2/3 mx-auto">
            <div className="flex flex-wrap -m-2">
              <div className="p-2 w-1/2">
                <div className="relative">
                  <label
                    htmlFor="name"
                    className="leading-7 text-sm text-gray-600 font-semibold"
                  >
                    Item Name*
                  </label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    className="input-give"
                  />
                </div>
              </div>
              <div className="p-2 w-1/2">
                <div className="relative">
                  <label
                    htmlFor="email"
                    className="leading-7 text-sm text-gray-600 font-semibold"
                  >
                    Estimated Item Value*
                  </label>
                  <input
                    type="number"
                    id="value"
                    name="number"
                    className="input-give"
                  />
                </div>
              </div>
              <div className="p-2 w-full">
                <div className="relative">
                  <label
                    htmlFor="message"
                    className="leading-7 text-sm text-gray-600 font-semibold"
                  >
                    Item Description*
                  </label>
                  <textarea
                    id="message"
                    name="message"
                    className="input-give"
                  ></textarea>
                </div>
              </div>

              <div className="p-2 w-1/2 my-2">
                <div className="relative">
                  <label
                    htmlFor="name"
                    className="leading-7 text-sm text-gray-600 font-semibold"
                  >
                    <span>Item Size*</span>
                    <select
                      name="cars"
                      id="cars"
                      form="carform"
                      className="form-select block w-full input-give p-2"
                    >
                      <option value="volvo">Select Item Size</option>
                      <option value="volvo">Small</option>
                      <option value="saab">Medium</option>
                      <option value="opel">Large</option>
                      <option value="audi">Extra-Large</option>
                    </select>
                  </label>
                </div>
              </div>
              <div className="p-2 w-1/2 my-2">
                <div className="relative">
                  <label
                    htmlFor="name"
                    className="leading-7 text-sm text-gray-600 font-semibold"
                  >
                    <span>Item Color*</span>
                    <select
                      name="cars"
                      id="cars"
                      form="carform"
                      className="form-select block w-full input-give p-2"
                    >
                      <option value="volvo">Select Item Color</option>
                      <option value="volvo">Greed</option>
                      <option value="saab">Black</option>
                      <option value="saab">Blue</option>
                      <option value="opel">Yellow</option>
                      <option value="audi">Red</option>
                    </select>
                  </label>
                </div>
              </div>
              <div className="p-2 w-1/2">
                <div className="relative">
                  <label
                    htmlFor="email"
                    className="leading-7 text-sm text-gray-600 font-semibold"
                  >
                    Out of 10 condition*
                  </label>
                  <input
                    type="number"
                    id="value"
                    name="number"
                    className="input-give"
                  />
                </div>
              </div>
              <div className="p-2 w-1/2">
                <div className="relative">
                  <label
                    htmlFor="name"
                    className="leading-7 text-sm text-gray-600 font-semibold"
                  >
                    <span>Item Condition*</span>
                    <select
                      name="cars"
                      id="cars"
                      form="carform"
                      className="form-select block w-full input-give p-2"
                    >
                      <option value="volvo">Select Item Condition</option>
                      <option value="volvo">Excellent</option>
                      <option value="saab">Great</option>
                      <option value="saab">Good</option>
                      <option value="opel">Fair</option>
                      <option value="audi">Bad</option>
                    </select>
                  </label>
                </div>
              </div>
              <div className="p-2 w-full">
                <div className="relative">
                  <label
                    htmlFor="name"
                    className="leading-7 text-sm text-gray-600 font-semibold"
                  >
                    Item Location*
                  </label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    className="input-give"
                  />
                </div>
              </div>
              <div className="p-2 m-3 w-full">
                <button className="submit-btn">
                  <FaSave className="mt-1 mr-2" />
                  SUBMIT ENTRIES
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>
    </MainLayout>
  )
}

export default give
