import GivingPage from '@/components/dashboard/GivingPage'
import { API_URL } from '@/config/index'
import { parseCookies } from '@/helpers/index'
import { DASH_PER_PAGE } from '@/config/index'
import Head from 'next/head'
import MainLayout from '../../components/layout/MainLayout'
import Pagination from '@/components/layout/Pagination'
import Wrapper from '@/components/dashboard/Wrapper'

export default function Givingpage({ items, token, page, total }) {
  return (
    <MainLayout>
      <Head>
        <title>Giving</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper title="Giving">
        <GivingPage items={items} token={token} page={page} total={total} />
      </Wrapper>
    </MainLayout>
  )
}

export async function getServerSideProps({ req, query: { page = 1 } }) {
  const { token } = parseCookies(req)

  if (!token) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  const start = +page === 1 ? 0 : (+page - 1) * DASH_PER_PAGE

  // Fetch total/count
  const totalRes = await fetch(`${API_URL}/items/countme`, {
    method: 'GET',
    headers: {
      Authorization: `Bearer ${token}`,
    },
  })
  const total = await totalRes.json()

  const res = await fetch(
    `${API_URL}/items/me?_limit=${DASH_PER_PAGE}&_start=${start}`,
    {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${token}`,
      },
    },
  )
  const items = await res.json()
  return {
    props: {
      items,
      token,
      page: +page,
      total,
    },
  }
}
