import GivingPage from '@/components/dashboard/GivingPage'
import { API_URL } from '@/config/index'
import { parseCookies } from '@/helpers/index'
import Head from 'next/head'
import MainLayout from '../../components/layout/MainLayout'

export default function Givingpage({ items, token }) {
  return (
    <MainLayout>
      <Head>
        <title>Giving</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font overflow-hidden">
        <div className="container px-3 py-6 mx-auto max-w-screen-xl">
          <div className="container mx-auto px-4 sm:px-8 max-w-3xl">
            <GivingPage items={items} token={token} />
          </div>
        </div>
      </section>
    </MainLayout>
  )
}

export async function getServerSideProps({ req, query: { page = 1 } }) {
  const { token } = parseCookies(req)

  if (!token) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  const start = +page === 1 ? 0 : (+page - 1) * PER_PAGE

  // // Fetch total/count
  // const totalRes = await fetch(`${API_URL}/requests/count`, {
  //   method: 'GET',
  //   headers: {
  //     Authorization: `Bearer ${token}`,
  //   },
  // })
  // const total = await totalRes.json()

  const res = await fetch(`${API_URL}/items/me`, {
    method: 'GET',
    headers: {
      Authorization: `Bearer ${token}`,
    },
  })
  const items = await res.json()
  return {
    props: {
      items,
      token,
    },
  }
}
