import Giving from '@/components/dashboard/Giving'
import Wrapper from '@/components/dashboard/Wrapper'
import Head from 'next/head'
import MainLayout from '../../components/layout/MainLayout'
import Recieving from '@/components/dashboard/Recieving'

export default function Dashboard() {
  return (
    <MainLayout>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper title="Dashboard">
        <Giving />
        <Recieving />
      </Wrapper>
    </MainLayout>
  )
}
