import Giving from '@/components/dashboard/Giving'
import Wrapper from '@/components/dashboard/Wrapper'
import Head from 'next/head'
import MainLayout from '../../components/layout/MainLayout'
import Recieving from '@/components/dashboard/Recieving'
import { parseCookies } from '@/helpers/index'
import { API_URL } from '@/config/index'

export default function Dashboard({ items, requests }) {
  let itemList = items.slice(0, 3)
  let reqList = requests.slice(0, 3)
  return (
    <MainLayout>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper title="Dashboard">
        <Giving items={itemList} />
        <Recieving requests={reqList} />
      </Wrapper>
    </MainLayout>
  )
}

export async function getServerSideProps({ req }) {
  const { token } = parseCookies(req)

  if (!token) {
    return {
      redirect: {
        destination: '/account/login',
        permanent: false,
      },
    }
  }

  const [itemsRes, requestsRes] = await Promise.all([
    fetch(`${API_URL}/items/me?_limit=3&_start=0`, {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${token}`,
      },
    }),
    fetch(`${API_URL}/requests/me?_limit=3&_start=0`, {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${token}`,
      },
    }),
  ])
  const [items, requests] = await Promise.all([
    itemsRes.json(),
    requestsRes.json(),
  ])

  return {
    props: {
      items,
      requests,
    },
  }
}
